language: node_js
node_js:
  - "8.11"
dist: trusty
sudo: true

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
  
script:
  - ng build --prod --base-href $base_href #base_href should be given in travis as an environment variable
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on: 
    branch: master