language: node_js
node_js:
  - "8.11"
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: 0f760b23-2242-4227-b27c-2eada217967b
  app: campaign-organizer